### ISSUE TITLE
third axis as U?

### ISSUE THREAD

**Issue by crkie** [LETARTARE/grblQ-Mega-4axes#2]
Hello,
is it possible to set the third axis as U? I cannot find somthing for this.
I would be send G1 X Y U V commands.

Thanks

**Comment by LETARTARE** [comment]
Hello,
no, the command "G1 X Y U V" is impossible because one can not have that a fourth single axis. 
You may simultaneously  XYU or XYV. The axes "A, B, C, U, V, W" are exclusive.
Cordially.
