### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by Moofasta** [LETARTARE/grblQ-Mega-4axes#3]
Hello, friend
Arduino IDE returns error when try to upload a zip library.... latest version... the same thing with original grbl 1.1j

**Comment by LETARTARE** [comment]
Hello,
https://github.com/gnea/grbl/wiki/Compiling-Grbl

**Comment by Moofasta** [comment]
I did it already several times:) ide doesnt recognise a proper library
anyway. Windows 10 issue maybe.. iil try it on other system
