### ISSUE TITLE
GRBLQ

### ISSUE THREAD

**Issue by sergiv69** [LETARTARE/grblQ-Mega-4axes#4]
Dear Letartare,

Your GRBLQ is probably what I was searching for long time ago. Thanks for that.
I wish to run that version with small modifications for ATmega1284 and to get your support too, of course paying for your service.

Can you contact me at: svalls@elite.es

Thanks!

**Comment by LETARTARE** [comment]
Hello,
make a clone and you can modify it as you please. Remember that this software is under the GPL3 license.
For support, keep asking here, I do not communicate by email.
Have a good day.

**Comment by sergiv69** [comment]
Hi,

Of course we should share it!
Problem is: how your 4th axis manages to do lines or arcs?
So for example interpolating B with Z

See:
http://www.buildlog.net/blog/2017/08/polar-pen-machine-kinematics/

El ds., 1 de set. 2018, 15:36, LETARTARE <notifications@github.com> va
escriure:

**Comment by kikirikiki** [comment]
Hi Letartare,

thank you very much for your projekt! I am not sure how is the wiring for the Endstop for the 4th axe.
Could you please help me? 

Thanks a lot!

**Comment by LETARTARE** [comment]
@kikirikiki 
Look at the picture :  https://github.com/LETARTARE/grblQ-Mega-4axes/wiki/Features.

> **pin 13 = Limit Q-Axis**

**Comment by kikirikiki** [comment]
Thanks a lot! What if I use a CNC-Shield? Is it posible?

**Comment by LETARTARE** [comment]
@kikirikiki 
Directly not.
It is necessary to locate the different corresponding pins on the shield and to make the wiring oneself.

**Comment by kikirikiki** [comment]
@LETARTARE 
Do you know which Pin I will have to use? How do you do the wiring without a shield?
Could I use one of the end-stops-pin (for example Z-Min) for my A-axis?

**Comment by LETARTARE** [comment]
@kikirikiki
GrblQ uses **only one rotary axis** at a time, so there is only one stop input for 'A', 'B', 'C'.
> pin 13 = Limit -Axis 

For the wiring you have to connect the limit switch ('A') to this pin 13, as you have to wire the limit switch Z on pin 12, the limit switch Y on pin 11,  the limit switch X on pin 10, 
See information sur https://github.com/gnea/grbl/wiki/Wiring-Limit-Switches by replacing the Uno card
by the Mega
**You can not use Zmin for 'A'.**

**Comment by kikirikiki** [comment]
@LETARTARE
Thanks a lot!! Do you know if your GRBLQ will work on a Raspberry Pi CNC Hat from Protoneer?
This one: https://wiki.protoneer.co.nz/Raspberry_Pi_CNC

**Comment by LETARTARE** [comment]
@kikirikiki 
I never tried. But I do not think so.

**Comment by kikirikiki** [comment]
@LETARTARE 
and with a RAMPs 1.4 will it work? 
Thanks a lot!

**Comment by Danieldelriovelilla** [comment]
@kikirikiki @LETARTARE  the code works with RAMPS 1.4 at the end?

**Comment by kikirikiki** [comment]
@danieldelriovelilla Yes, it works perfekt!
